services:
 
  dev-db:  # Serviço do banco de dados
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: naur
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
    networks:
      - db_network  # ✅ Nome mais descritivo para a rede

networks:
  db_network:  # ✅ Nome da rede definido corretamente
    driver: bridge
